name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Orion"
          module-name: Orion Documentation
          output: Documentation
          minimum-access-level: private
          format: "html"
      - name: Commit Documentation
        run: |
          sudo chown -R $USER:$USER ./Documentation
          git config --global user.name 'cstanze'
          git config --global user.email 'cstanze@users.noreply.github.com'
          git add ./Documentation/* 
          git commit -m "[Automated] Documentation CI"
          git branch -M gh-pages
          git push origin HEAD
      # - name: Upload Documentation to Wiki
      #  uses: SwiftDocOrg/github-wiki-publish-action@v1
      #  with:
      #    path: "Documentation"
      #  env:
      #    GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

