name: Documentation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Generate Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Orion"
          module-name: Orion Documentation
          output: Documentation
          minimum-access-level: private
      - uses: EndBug/add-and-commit@v8 # You can change this to use a specific version.
        with:
          add: "Documentation"
    
          # Determines the way the action fills missing author name and email. Three options are available:
          # - github_actor -> UserName <UserName@users.noreply.github.com>
          # - user_info -> Your Display Name <your-actual@email.com>
          # - github_actions -> github-actions <email associated with the github logo>
          default_author: github_actions
          message: 'Add documentation from SwiftDoc'
          push: true 
      # - name: Upload Documentation to Wiki
      #  uses: SwiftDocOrg/github-wiki-publish-action@v1
      #  with:
      #    path: "Documentation"
      #  env:
      #    GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

